import {
  Calculator,
  BookOpen,
  Languages,
  Beaker,
  Atom,
  Microscope,
  Globe,
  Landmark,
  Palette,
  Camera,
  Music,
  Computer,
  Dumbbell,
  Gamepad2
} from 'lucide-react';

export const subjectIconMap = {
  'Math': Calculator,
  'Mathematics': Calculator,
  'Algebra': Calculator,
  'Geometry': Calculator,
  'Calculus': Calculator,
  'Statistics': Calculator,
  'Reading': BookOpen,
  'Literature': BookOpen,
  'English': BookOpen,
  'Language Arts': Languages,
  'Spanish': Languages,
  'French': Languages,
  'German': Languages,
  'Science': Beaker,
  'Chemistry': Beaker,
  'Physics': Atom,
  'Biology': Microscope,
  'Anatomy': Microscope,
  'Botany': Microscope,
  'Geography': Globe,
  'History': Landmark,
  'Social Studies': Globe,
  'Civics': Landmark,
  'Government': Landmark,
  'Art': Palette,
  'Drawing': Palette,
  'Painting': Palette,
  'Photography': Camera,
  'Music': Music,
  'Band': Music,
  'Orchestra': Music,
  'Computer Science': Computer,
  'Programming': Computer,
  'Technology': Computer,
  'Physical Education': Dumbbell,
  'PE': Dumbbell,
  'Health': Dumbbell,
  'Fitness': Dumbbell,
  'Games': Gamepad2,
  'Recreation': Gamepad2,
  'default': BookOpen
};

export const getSubjectIcon = (subject) => {
  return subjectIconMap[subject] || subjectIconMap['default'];
};